<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Checklist\Module'                        => __DIR__ . '/Module.php',
    'Checklist\Controller\TaskController' => __DIR__ . '/src/Checklist/Controller/TaskController.php',
    'ChecklistTest\Framework\TestCase'        => __DIR__ . '/tests/Checklist/Framework/TestCase.php',
    'ChecklistTest\SampleTest'                => __DIR__ . '/tests/Checklist/SampleTest.php',
);
