<strong>Module:</strong>        Developer &raquo;
<strong>Controller:</strong>    Markdown &raquo;
<strong>Action:</strong>        index

<br/>
<br/>
<div class="collapse navbar-collapse">
	<h1>Index of documents</h1>	 
	<?php 
		echo $this->navigation('navigation')
			->menu()
	        ->setMinDepth(2)
	        ->setUlClass('nav navbar-nav');
	?>  
</div>

<div class="container">
<?
 	if(isset($this->data))
 		echo $this->markdown($this->data); 
?>
</div>