<strong>Module:</strong>        Developer &raquo;
<strong>Controller:</strong>    Debug &raquo;
<strong>Action:</strong>        index

<br/>
<br/>
<div class="collapse navbar-collapse">
<?php
$internal = $this->navigation('navigation')->findOneByLabel('Debug');
    echo $this->navigation('navigation')
           ->menu()
           ->setMinDepth(2)
           ->setMaxDepth(2)
           ->setUlClass('nav nav-tabs')
           ->renderSubMenu(null, 'sidebar', 4);
 ?>  
</div>

<div class="container">
<?
 	if(isset($this->data))
 		echo $this->markdown($this->data); 
?>
</div>