<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Album\Module'                        => __DIR__ . '/Module.php',
    'Album\Controller\SkeletonController' => __DIR__ . '/src/Album/Controller/SkeletonController.php',
    'AlbumTest\Framework\TestCase'        => __DIR__ . '/tests/Album/Framework/TestCase.php',
    'AlbumTest\SampleTest'                => __DIR__ . '/tests/Album/SampleTest.php',
);
