<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cheetara\Module'                        => __DIR__ . '/Module.php',
    'Cheetara\Controller\IndexController' => __DIR__ . '/src/Cheetara/Controller/IndexController.php',
    'CheetaraTest\Framework\TestCase'        => __DIR__ . '/tests/Cheetara/Framework/TestCase.php',
    'CheetaraTest\SampleTest'                => __DIR__ . '/tests/Cheetara/SampleTest.php',
);
