<?php
$title = 'Add new task';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('task', array('action' => 'add')));
$form->get('submit')->setAttribute('value', 'Add');
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
?>
<div>
<?php echo $this->formInput($form->get('submit')); ?>
</div>
<?php
echo $this->form()->closeTag($form);