<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3">
            <div class="bs-sidebar hidden-print affix-top" role="complementary">
                <?php echo $this->partial('partial/developer/menu.phtml'); ?>
            </div>
        </div>
        <div class="col-md-9" role="main">
        
            <!-- Global Bootstrap settings
            ================================================== -->
            <?php echo $this->partial('partial/developer/di.phtml'); ?>
            
            <!-- Grid system
            ================================================== -->
            <?php //echo $this->partial('partial/developer/unittest.phtml'); ?>
            
            <!-- Typography
            ================================================== -->
            <?php //echo $this->partial('partial/developer/directorystructure.phtml'); ?>
            
            <!-- Code
            ================================================== -->
            <?php //echo $this->partial('partial/developer/datamapper.phtml'); ?>
            
            <!-- Tables
            ================================================== -->
            <?php //echo $this->partial('partial/developer/codesnnipet.phtml'); ?>
        
        </div>
    </div>
</div>