<div class="container bs-docs-container">
    <div class="row">
        
<div class="panel">
	<h3 class="panel-title"><?php echo $this->translate('Versions') ?></h3>
	<ul>
		<li>Zend Framework <strong>Last Version</strong>: <?=Zend\Version\Version::getLatest();?></li>
		<li>Zend Framework <strong>Current Version</strong>: <?=Zend\Version\Version::VERSION;?></li>
	</ul>
</div>
    </div>
</div>